#!/usr/bin/env bash
# scripts/decisions-index.sh — (re)generate INDEX.md next to the DEC files: one
# row per decision, so a log that has grown past a couple of dozen entries stays
# navigable and cheap to cold-read.
#
# Why: answering "what have we already decided about X?" currently means opening
# every DEC file. The largest dogfood instance carries 86 of them. This is the
# in-repo answer to that wall (ContextCore's own graduation trigger is ">30
# entries and grepping feels slow") — it defers graduating to real infrastructure
# rather than replacing it.
#
# Active and superseded decisions are split into two tables on purpose: the
# question a cold reader asks first is "what is in force", and one flat list
# buries it. `affected_scope` is deliberately NOT a column — multi-valued path
# globs are unreadable at this row count, and "which paths are governed" is a
# different view (a traceability walk, not an index).
#
# The generated file is derived, never hand-edited. `--check` writes nothing and
# exits 1 when the committed index no longer matches the decisions on disk, so
# CI can keep it honest:
#
#   just decisions-index            # regenerate INDEX.md in place
#   just decisions-index --check    # CI: fail if it's stale
#
# The index is opt-in by existence: --check passes quietly on a repo that has
# never generated one, and only fails once a committed index falls behind. That
# keeps the CI gate shippable to every instance.
#
# Exit status: 0 clean · 1 stale (--check only) · 2 usage error.

set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=scripts/_lib.sh
source "${SCRIPT_DIR}/_lib.sh"

# Works in an instance and in the template repo itself (docs/decisions/).
require_decisions_context

CHECK=0
JSON_OUT=$(has_json_flag "$@")
for a in "$@"; do
    case "$a" in
        --check) CHECK=1 ;;
        --json)  : ;;
        '')      : ;;
        *)       usage_error "just decisions-index [--check] [--json]" ;;
    esac
done

DECISIONS_DIR="$(decisions_dir)"
INDEX_FILE="${DECISIONS_DIR}/INDEX.md"

decs=()
while IFS= read -r f; do [ -n "$f" ] && decs+=("$f"); done < <(find_all_decisions)

if [ "${#decs[@]}" -eq 0 ]; then
    die "no DEC-*.md files found in ${DECISIONS_DIR#"${REPO_ROOT}/"}/ — nothing to index."
fi

# Escape the pipe so a title containing one can't break the table row.
md_cell() { printf '%s' "$1" | sed 's/|/\\|/g'; }

# Local readers for the two fields _lib.sh doesn't expose (the audit script has
# its own copies; duplicating two awk one-liners beats widening the shared lib
# for a single caller).
get_top_scalar_local() {
    awk -v k="$2" '
        /^---$/ { f = !f; next } !f { exit }
        $0 ~ "^" k ":" { v = $2; if (v != "null" && v != "") print v; exit }
    ' "$1"
}
get_dec_project_id_local() {
    awk '
        /^---$/ { f = !f; next } !f { exit }
        /^project:/ { p = 1; next }
        p && /^[a-zA-Z_]/ { p = 0 }
        p && /^[[:space:]]+id:/ { v = $2; if (v != "null" && v != "") print v; exit }
    ' "$1"
}

# Render the whole index to stdout. Callers either write it or diff it.
render_index() {
    local f id title conf status sb sup proj rel
    local active_rows="" superseded_rows="" n_active=0 n_superseded=0

    for f in "${decs[@]}"; do
        id=$(get_dec_id "$f")
        title=$(md_cell "$(get_dec_title "$f")")
        conf=$(get_dec_confidence "$f"); [ -n "$conf" ] && [ "$conf" != null ] || conf="—"
        status=$(get_dec_effective_status "$f")
        sb=$(get_dec_superseded_by "$f")
        sup=$(get_top_scalar_local "$f" supersedes)
        proj=$(get_dec_project_id_local "$f"); [ -n "$proj" ] || proj="—"
        rel=$(basename "$f")

        if [ -n "$sb" ]; then
            superseded_rows="${superseded_rows}| [${id}](${rel}) | ${title} | ${conf} | ${proj} | ${sb} |"$'\n'
            n_superseded=$((n_superseded + 1))
        else
            [ -n "$sup" ] || sup="—"
            active_rows="${active_rows}| [${id}](${rel}) | ${title} | ${conf} | ${status} | ${proj} | ${sup} |"$'\n'
            n_active=$((n_active + 1))
        fi
    done

    printf '# Decision index\n\n'
    printf '<!-- GENERATED by `just decisions-index` — do not edit by hand. -->\n\n'
    printf '%d decision(s): **%d active**, **%d superseded**.\n' \
        "${#decs[@]}" "$n_active" "$n_superseded"
    printf 'Regenerate after adding or superseding one; `just decisions-index --check` fails if this file is stale.\n\n'

    printf '## Active\n\n'
    if [ "$n_active" -gt 0 ]; then
        printf '| ID | Title | Confidence | Status | Project | Supersedes |\n'
        printf '|---|---|---|---|---|---|\n'
        printf '%s\n' "${active_rows%$'\n'}"
    else
        printf '*(none)*\n'
    fi

    if [ "$n_superseded" -gt 0 ]; then
        printf '\n## Superseded\n\n'
        printf 'Kept for the record — no decision is ever deleted.\n\n'
        printf '| ID | Title | Confidence | Project | Superseded by |\n'
        printf '|---|---|---|---|---|\n'
        printf '%s\n' "${superseded_rows%$'\n'}"
    fi
}

# --- JSON output (DEC-001 §2) ------------------------------------------------
# The same rows the markdown carries, plus `affected_scope`. The scope list is
# deliberately absent from the human table (unreadable at 86 rows) but belongs
# here: width costs nothing in a machine surface, and it is the edge a future
# traceability walk needs. Read-only — --json never writes INDEX.md.
if [ "$JSON_OUT" = 1 ]; then
    items=()
    for f in "${decs[@]}"; do
        sb=$(get_dec_superseded_by "$f")
        sup=$(get_top_scalar_local "$f" supersedes)
        proj=$(get_dec_project_id_local "$f")
        conf=$(get_dec_confidence "$f")
        scope_parts=()
        while IFS= read -r g; do [ -n "$g" ] && scope_parts+=("$(json_qs "$g")"); done < <(get_dec_affected_scope "$f")
        [ "${#scope_parts[@]}" -gt 0 ] && scope_arr=$(json_arr "${scope_parts[@]}") || scope_arr="[]"
        case "$conf" in ''|null) confj=null ;; *) confj=$conf ;; esac
        items+=("$(json_obj \
            "insight.id" "$(json_qs "$(get_dec_id "$f")")" \
            title "$(json_qs "$(get_dec_title "$f")")" \
            status "$(json_qs "$(get_dec_effective_status "$f")")" \
            "insight.confidence" "$confj" \
            "project.id" "$([ -n "$proj" ] && json_qs "$proj" || printf null)" \
            supersedes "$([ -n "$sup" ] && json_qs "$sup" || printf null)" \
            superseded_by "$([ -n "$sb" ] && json_qs "$sb" || printf null)" \
            affected_scope "$scope_arr" \
            file "$(json_qs "$(basename "$f")")")")
    done
    [ "${#items[@]}" -gt 0 ] && arr=$(json_arr "${items[@]}") || arr="[]"
    json_emit decisions-index "$(json_obj \
        count "${#decs[@]}" \
        index_path "$(json_qs "${INDEX_FILE#"${REPO_ROOT}/"}")" \
        decisions "$arr")"
    exit 0
fi

rendered=$(render_index)

if [ "$CHECK" = 1 ]; then
    # The index is OPT-IN BY EXISTENCE: a repo that has never generated one
    # isn't failing at anything, so --check passes quietly. Once the file is
    # committed, CI keeps it honest. This is what makes the gate safe to ship
    # to every instance without breaking the ones that don't want an index.
    if [ ! -f "$INDEX_FILE" ]; then
        info "decisions-index: no ${INDEX_FILE#"${REPO_ROOT}/"} committed — nothing to keep in sync."
        info "  Run 'just decisions-index' to start one (worth it past ~25 decisions; you have ${#decs[@]})."
        exit 0
    fi
    if [ "$rendered" != "$(cat "$INDEX_FILE")" ]; then
        die "decisions-index: ${INDEX_FILE#"${REPO_ROOT}/"} is stale. Run 'just decisions-index'."
    fi
    success "decisions-index: ${INDEX_FILE#"${REPO_ROOT}/"} is up to date (${#decs[@]} decisions)."
    exit 0
fi

printf '%s\n' "$rendered" > "$INDEX_FILE"
success "decisions-index: wrote ${INDEX_FILE#"${REPO_ROOT}/"} (${#decs[@]} decisions)."
